# We have added all type of reporters in the Playwright config file. Here we are running the tests and
# Extracting passed, failed, and skipped tests.  Copying the artifacts to the workflow artifacts.
# Sending test results to Slack using a webhook.

# Name of the workflow
name: Playwright Tests

# Define the events that trigger this workflow
on:
  pull_request: # Trigger the workflow on pull requests to the main branch
    branches: [ main ]
  push: # Trigger the workflow on pushes to the main branch
    branches: [ main ]

# Define the jobs in this workflow
jobs:
  test: # Job name
    runs-on: ubuntu-latest # Use the latest Ubuntu runner provided by GitHub

    # Define the steps to execute in this job
    steps:
      # Step 1: Check out the repository code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Specify the Node.js version to use
          cache: 'npm' # Enable caching for npm dependencies

      # Step 3: Install project dependencies
      - name: Install deps
        run: npm ci # Install dependencies using npm clean install

      # Step 4: Install Playwright browsers
      - name: Install browsers
        run: npx playwright install --with-deps chromium # Install Playwright and Chromium browser dependencies

      # Step 5: Run Playwright tests and generate reports
      - name: Run Playwright tests (JSON + HTML + Allure)
        run: |
          npx playwright test || true

      # Step 6: Extract test results from JSON report
      - name: Extract test results
        id: results
        run: |
          passed=$(jq '[.. | .status? | select(.=="passed")] | length' results.json)
          failed=$(jq '[.. | .status? | select(.=="failed")] | length' results.json)
          skipped=$(jq '[.. | .status? | select(.=="skipped")] | length' results.json)

          echo "passed=$passed" >> $GITHUB_OUTPUT
          echo "failed=$failed" >> $GITHUB_OUTPUT
          echo "skipped=$skipped" >> $GITHUB_OUTPUT

      # Step 7a: Upload Html test reports as artifacts    
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/

      # Step 7b: Upload json report as artifact    
      - name: Upload JSON results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-json-results
          path: results.json

      - name: Deploy Playwright HTML report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          publish_branch: gh-pages

      # Step 8: Notify Slack with summary + link to HTML report artifact
      - name: Notify Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\": \"Playwright CI Results\n\n:white_check_mark: Passed: *${{ steps.results.outputs.passed }}*\n:x: Failed: *${{ steps.results.outputs.failed }}*\n:fast_forward: Skipped: *${{ steps.results.outputs.skipped }}*\n\n*Repo*: ${{ github.repository }}\n*Branch*: ${{ github.ref_name }}\n*Author*: ${{ github.actor }}\n\n:page_facing_up: *HTML Report*: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Download Artifact>\n\n*Logs*: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Logs>\n\n HTML2: *<https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      # Step 10: Slack notification - Another way to do it
      # - name: Notify Slack
      #   if: always()
      #   run: |
      #     curl -X POST -H 'Content-type: application/json' \
      #     --data "{
      #       \"text\": \"Playwright CI Results\n\n:white_check_mark: Passed: *${{ steps.results.outputs.passed }}*\n:x: Failed: *${{ steps.results.outputs.failed }}*\n:fast_forward: Skipped: *${{ steps.results.outputs.skipped }}*\n\n*Repo*: ${{ github.repository }}\n*Branch*: ${{ github.ref_name }}\n*Author*: ${{ github.actor }}\n\n:page_facing_up: *HTML Report*: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Download Artifact>\n*Allure Report*: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Download Artifact>\n\n*Logs*: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Logs>\"
      #     }" \
      #     ${{ secrets.SLACK_WEBHOOK_URL }}

